services:
  - type: web
    name: bumchik-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    autoDeploy: true
    envVars: []
    healthCheckPath: /
